finished the cluster cfn except fro the certifcate ARN

diff --git a/bin/cfn/networking-deploy b/bin/cfn/networking-deploy
--- a/bin/cfn/networking-deploy
+++ b/bin/cfn/networking-deploy
@@ -1,5 +1,5 @@
-#! /usr/bin/bash
-set -e # stop yhe execution if it fails
+#! /usr/bin/env bash
+set -e # stop the execution of the script if it fails
 
 CFN_PATH="/workspace/aws-bootcamp-cruddur-2023/aws/cfn/networking/template.yaml"
 echo $CFN_PATH
@@ -7,8 +7,9 @@ echo $CFN_PATH
 cfn-lint $CFN_PATH
 
 aws cloudformation deploy \
-  --stack-name "Cruddur" \
-  --s3-bucket "$CFN_BUCKET" \
+  --stack-name "CrdNet" \
+  --s3-bucket $CFN_BUCKET \
   --template-file "$CFN_PATH" \
   --no-execute-changeset \
+  --tags group=cruddur-networking \
   --capabilities CAPABILITY_NAMED_IAM
